version: '3.7'
networks:
  default:
    external:
      name: mysql-default
services:
  mysql_db_container:
    image: mysql:latest
    container_name: "mysql_db_container"
    command: --default-authentication-plugin=mysql_native_password
    # command: /bin/bash -x /tmp/mysql_connector.sh
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: restipi_wr
      MYSQL_USER: restipi
      MYSQL_PASSWORD: restipi
      DATABASE_HOST: mysql_db_container
    ports:
      - 3306:3306
    expose:
      # open port on the docker
      - 3306 
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    depends_on:
      - mysql_db_container
    environment:
      PMA_HOST: mysql_db_container
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
  my_db_config:
    build: .
    depends_on:
      - mysql_db_container
  #   volumes:
  #     - ./mysql_connector.sh:/tmp/mysql_connector.sh
  #   command: /bin/bash -x /tmp/mysql_connector.sh

volumes:
  db_data:
